version: "3.8"

services:
    backend:
        depends_on:
            db:
                condition: service_healthy
        build:
            dockerfile: dockerfile
            context: ./backend
        environment: 
            DATABASE_URL: "postgresql://postgres:docker@db:5432/chatbot?schema=public"
            NODE_ENV: development
            PORT: 8080
        ports:
            - "8080:8080"
    frontend:
        depends_on:
            - db
            - backend
        build:
            dockerfile: dockerfile
            context: ./webcomponent
        environment: 
            NODE_ENV: development
            PORT: 3000
        ports:
            - "3000:3000"
    db:
        image: postgres:10.4
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d chatbot"]
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: chatbot

